apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: slack-config
  namespace: monitoring
  labels:
    alertmanagerConfig: slack
spec:
  route:
    receiver: slack
    groupBy: ["alertname"]
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 1h
  receivers:
    - name: slack
      slackConfigs:
        - apiURL:
            name: alertmanager-slack-secret
            key: slack_webhook
          channel: "#alerts"
          title: '{{ .GroupLabels.alertname }}'
          text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'

