apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager-slack-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: alertmanager-slack-secret
    creationPolicy: Owner
  data:
    - secretKey: slack_webhook
      remoteRef:
        key: alertmanager
        property: slack_webhook

