apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - traefik-servicemonitor.yaml
  - slo-rules.yaml
  - grafana-slo-dashboard.yaml
  - alertmanager-secret.yaml
  - alertmanager-config.yaml

