apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n8n-vault-secret
  namespace: n8n
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: n8n-vault-auth
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: N8N_ENCRYPTION_KEY
      remoteRef:
        key: n8n
        property: N8N_ENCRYPTION_KEY
    - secretKey: N8N_PORT
      remoteRef:
        key: n8n
        property: N8N_PORT
    - secretKey: N8N_PROTOCOL
      remoteRef:
        key: n8n
        property: N8N_PROTOCOL