apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: n8n

resources:
  - helmrepository.yaml
  - helmrelease.yaml

# Prevent Kustomize from adding random hashes to the ConfigMap name
generatorOptions:
  disableNameSuffixHash: true

# Convert your existing values file into a ConfigMap dynamically
configMapGenerator:
  - name: n8n-values-config
    files:
      - values.yaml=n8n-values.yaml
