apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-main
  namespace: n8n
spec:
  template:
    spec:
      containers:
        - name: n8n-main
          env:
            # Forcing these variables past the Helm chart restrictions
            - name: N8N_SECURE_COOKIE
              value: "false"
            - name: N8N_HOST
              value: "n8n.192.168.4.140.nip.io"
            - name: WEBHOOK_URL
              value: "http://n8n.192.168.4.140.nip.io/"
