apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rabbitmq-system
resources:
  - namespace.yaml
  - https://github.com/rabbitmq/cluster-operator/releases/download/v2.21.0/cluster-operator.yml

