apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: homelab
  namespace: rabbitmq-system
spec:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 1Gi
  persistence:
    storageClassName: local-path
    storage: 5Gi

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq-management
  namespace: rabbitmq-system
spec:
  ingressClassName: traefik
  rules:
    - host: rabbitmq.whatsoever.au
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homelab
                port:
                  number: 15672
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rabbitmq
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
    - port: prometheus
      interval: 30s
  namespaceSelector:
    matchNames:
      - rabbitmq-system
  selector:
    matchLabels:
      app.kubernetes.io/name: homelab
