apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: homelab
  namespace: rabbitmq-system
spec:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 1Gi
  persistence:
    storageClassName: local-path
    storage: 5Gi

