apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: technitium-config
  namespace: flux-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi