apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnpg-system

resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - plugin-barman-cloud.yaml   # B-R1-09: Barman Cloud plugin (CNPG-I)
