apiVersion: milvus.io/v1alpha1
kind: MilvusCluster
metadata:
  name: homelab
  namespace: milvus-operator
spec:
  dependencies:
    etcd:
      inCluster:
        values:
          replicaCount: 1
          persistence:
            enabled: true
            size: 5Gi
    pulsar:
      inCluster:
        values:
          components:
            autorecovery: false
            functions: false
            toolset: false
            pulsar_manager: false
          monitoring:
            prometheus: false
            grafana: false
            node_exporter: false
            alert_manager: false
          proxy:
            replicaCount: 1
            resources:
              requests:
                cpu: "0.01"
                memory: 256Mi
            configData:
              PULSAR_MEM: "-Xms256m -Xmx256m"
          bookkeeper:
            replicaCount: 2
            resources:
              requests:
                cpu: "0.01"
                memory: 256Mi
            configData:
              PULSAR_MEM: "-Xms256m -Xmx256m -XX:MaxDirectMemorySize=256m"
          zookeeper:
            replicaCount: 1
            resources:
              requests:
                cpu: "0.01"
                memory: 256Mi
            configData:
              PULSAR_MEM: "-Xms256m -Xmx256m"
          broker:
            replicaCount: 1
            resources:
              requests:
                cpu: "0.01"
                memory: 256Mi
            configData:
              PULSAR_MEM: "-Xms256m -Xmx256m"
    storage:
      inCluster:
        values:
          mode: standalone
          persistence:
            enabled: true
            size: 20Gi
  components:
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
  config: {}

