apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zitadel
resources:
  - namespace.yaml
  - externalsecret.yaml
  - externalsecret-config.yaml
  - externalsecret-authtls.yaml    # in-cluster TLS cert for the OIDC backchannel
  - postgres-cluster.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - nginx-configmap.yaml
  - nginx.yaml
  - ingress.yaml
